words:
  - AUTOINCREMENT
  - bindgen
  - chrono
  - dotenv
  - fieldset
  - gloo
  - hgroup
  - onchange
  - onclick
  - pico
  - prereqs
  - sched
  - serde
  - sqlx
  - teloxide
  - Trufot
  - trufotbot
  - trunc
