words:
  - AUTOINCREMENT
  - bindgen
  - chrono
  - clippy
  - cronparser
  - dotenv
  - fieldset
  - gloo
  - hgroup
  - itertools
  - newbot
  - onchange
  - onclick
  - ondelete
  - oninput
  - onsave
  - pico
  - prereqs
  - rstest
  - rustup
  - sched
  - serde
  - sqlx
  - Swatinem
  - teloxide
  - Trufot
  - trufotbot
  - trunc
  - wasmbind
