# Copyright (C) 2026 Ohad Lutzky <lutzky@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-only

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude: |
            (?x)^(
                frontend/trufotbot-openapi.json|
                frontend/src/openapi/.*
            )$
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
                frontend/trufotbot-openapi.json|
                frontend/src/openapi/.*
            )$
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: no-axum-debug-handler
        name: No axum debug handler
        description: You should use it, but not commit it.
        language: pygrep # cspell: word pygrep
        entry: "axum::debug_handler|debug_handler]"
        types: [rust]
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
      - id: cargo-clippy # cspell: word clippy
        name: cargo clippy
        description: Lints Rust code with cargo clippy.
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      # Run cargo-check and cargo-test for all filetypes; modifying non-rust
      # files can break the build.
      - id: cargo-check
        name: cargo check
        description: Checks the Rust project for errors.
        entry: cargo check --all-targets
        language: system
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        description: Run tests
        entry: cargo test
        language: system
        pass_filenames: false
        stages: [pre-push]
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.0.1
    hooks:
      - id: cspell # Spell check changed files


      # Slowest checks should only run in CI (github actions)
