# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: no-axum-debug-handler
        name: No axum debug handler
        description: You should use it, but not commit it.
        language: pygrep # cspell: word pygrep
        entry: "axum::debug_handler|debug_handler]"
        types: [rust]
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
      - id: cargo-clippy
        name: cargo clippy
        description: Lints Rust code with cargo clippy.
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      # Slower hooks running only at pre-push
      - id: cargo-check
        stages: [pre-push]
        name: cargo check
        description: Checks the Rust project for errors.
        entry: cargo check --all-targets
        language: system
        types: [rust]
        pass_filenames: false

      # Slowest checks should only run in CI (github actions)
