// Copyright (C) 2026 Ohad Lutzky <lutzky@gmail.com>
//
// SPDX-License-Identifier: GPL-3.0-only

use anyhow::Result;
use vergen_gitcl::{Emitter, GitclBuilder};

fn main() -> Result<()> {
    // trigger recompilation when a new migration is added
    // generated by `sqlx migrate build-script`
    println!("cargo:rerun-if-changed=migrations");

    Emitter::default()
        .add_instructions(
            &GitclBuilder::default()
                .describe(false, true, None)
                .build()?,
        )?
        .emit()?;

    Ok(())
}
