// Copyright (C) 2026 Ohad Lutzky <lutzky@gmail.com>
//
// SPDX-License-Identifier: GPL-3.0-only

use anyhow::Result;
use vergen_gitcl::{BuildBuilder, Emitter, GitclBuilder};

fn main() -> Result<()> {
    // rerun the build script (and re-emit the build timestamp) when
    // sources change, or when a new migration is added; the migration
    // directive is generated by `sqlx migrate build-script`
    println!("cargo:rerun-if-changed=src");
    println!("cargo:rerun-if-changed=migrations");

    Emitter::default()
        .add_instructions(
            &GitclBuilder::default()
                .describe(false, true, None)
                .build()?,
        )?
        .add_instructions(&BuildBuilder::default().build_timestamp(true).build()?)?
        .emit()?;

    Ok(())
}
