# Copyright (C) 2026 Ohad Lutzky <lutzky@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-only

site_name: TrufotBot
theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
nav:
  - Home:
    - index.md
    - getting-started.md
  - User guide:
    - Interacting with the Bot: interacting.md
    - telegram-setup.md
    - environment-variables.md
  - Development:
    - Development Setup: development.md
    - API Client: api-client.md
    - Release Building: release.md
site_url: https://lutzky.net/trufotbot/
repo_url: https://github.com/lutzky/trufotbot
markdown_extensions:
- admonition
- attr_list
- def_list
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
