// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { MedicationCreateData, MedicationCreateResponses, MedicationDeleteData, MedicationDeleteResponses, MedicationDeleteErrors, PatientsListData, PatientsListResponses, PatientsCreateData, PatientsCreateResponses, PatientsDeleteData, PatientsDeleteResponses, PatientsDeleteErrors, PatientsGetData, PatientsGetResponses, PatientsGetErrors, PatientsUpdateData, PatientsUpdateResponses, PatientsUpdateErrors, MedicationUpdateData, MedicationUpdateResponses, MedicationUpdateErrors, DosesListData, DosesListResponses, DosesListErrors, DosesRecordData, DosesRecordResponses, DosesRecordErrors, DosesDeleteData, DosesDeleteResponses, DosesDeleteErrors, DosesGetData, DosesGetResponses, DosesGetErrors, DosesUpdateData, DosesUpdateResponses, DosesUpdateErrors, RemindersSendData, RemindersSendResponses, RemindersSendErrors, RemindersGetData, RemindersGetResponses, RemindersGetErrors, RemindersSetData, RemindersSetResponses, RemindersSetErrors, StatusGetData, StatusGetResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';
import { patientsGetResponseTransformer, dosesListResponseTransformer, dosesGetResponseTransformer } from './transformers.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create a new medication
 */
export const medicationCreate = <ThrowOnError extends boolean = true>(options: Options<MedicationCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<MedicationCreateResponses, unknown, ThrowOnError>({
        url: '/api/medications',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete a medication
 */
export const medicationDelete = <ThrowOnError extends boolean = true>(options: Options<MedicationDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<MedicationDeleteResponses, MedicationDeleteErrors, ThrowOnError>({
        url: '/api/medications/{id}',
        ...options
    });
};

/**
 * List all patients
 */
export const patientsList = <ThrowOnError extends boolean = true>(options?: Options<PatientsListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<PatientsListResponses, unknown, ThrowOnError>({
        url: '/api/patients',
        ...options
    });
};

/**
 * Create a patient
 */
export const patientsCreate = <ThrowOnError extends boolean = true>(options: Options<PatientsCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PatientsCreateResponses, unknown, ThrowOnError>({
        url: '/api/patients',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete a patient
 */
export const patientsDelete = <ThrowOnError extends boolean = true>(options: Options<PatientsDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<PatientsDeleteResponses, PatientsDeleteErrors, ThrowOnError>({
        url: '/api/patients/{id}',
        ...options
    });
};

/**
 * Get a patient
 */
export const patientsGet = <ThrowOnError extends boolean = true>(options: Options<PatientsGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<PatientsGetResponses, PatientsGetErrors, ThrowOnError>({
        responseTransformer: patientsGetResponseTransformer,
        url: '/api/patients/{id}',
        ...options
    });
};

/**
 * Update a patient
 */
export const patientsUpdate = <ThrowOnError extends boolean = true>(options: Options<PatientsUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PatientsUpdateResponses, PatientsUpdateErrors, ThrowOnError>({
        url: '/api/patients/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Update a medication
 */
export const medicationUpdate = <ThrowOnError extends boolean = true>(options: Options<MedicationUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<MedicationUpdateResponses, MedicationUpdateErrors, ThrowOnError>({
        url: '/api/patients/{patient_id}/medications/{medication_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List doses
 */
export const dosesList = <ThrowOnError extends boolean = true>(options: Options<DosesListData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<DosesListResponses, DosesListErrors, ThrowOnError>({
        responseTransformer: dosesListResponseTransformer,
        url: '/api/patients/{patient_id}/medications/{medication_id}/doses',
        ...options
    });
};

/**
 * Record (create) a new dose
 */
export const dosesRecord = <ThrowOnError extends boolean = true>(options: Options<DosesRecordData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<DosesRecordResponses, DosesRecordErrors, ThrowOnError>({
        url: '/api/patients/{patient_id}/medications/{medication_id}/doses',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete dose
 */
export const dosesDelete = <ThrowOnError extends boolean = true>(options: Options<DosesDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DosesDeleteResponses, DosesDeleteErrors, ThrowOnError>({
        url: '/api/patients/{patient_id}/medications/{medication_id}/doses/{dose_id}',
        ...options
    });
};

/**
 * Get dose
 */
export const dosesGet = <ThrowOnError extends boolean = true>(options: Options<DosesGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<DosesGetResponses, DosesGetErrors, ThrowOnError>({
        responseTransformer: dosesGetResponseTransformer,
        url: '/api/patients/{patient_id}/medications/{medication_id}/doses/{dose_id}',
        ...options
    });
};

/**
 * Update dose
 */
export const dosesUpdate = <ThrowOnError extends boolean = true>(options: Options<DosesUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<DosesUpdateResponses, DosesUpdateErrors, ThrowOnError>({
        url: '/api/patients/{patient_id}/medications/{medication_id}/doses/{dose_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Send a reminder
 */
export const remindersSend = <ThrowOnError extends boolean = true>(options: Options<RemindersSendData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<RemindersSendResponses, RemindersSendErrors, ThrowOnError>({
        url: '/api/patients/{patient_id}/medications/{medication_id}/remind',
        ...options
    });
};

/**
 * Get reminders for patient's medication
 */
export const remindersGet = <ThrowOnError extends boolean = true>(options: Options<RemindersGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<RemindersGetResponses, RemindersGetErrors, ThrowOnError>({
        url: '/api/patients/{patient_id}/medications/{medication_id}/reminders',
        ...options
    });
};

/**
 * Set reminders for patient's medication
 */
export const remindersSet = <ThrowOnError extends boolean = true>(options: Options<RemindersSetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<RemindersSetResponses, RemindersSetErrors, ThrowOnError>({
        url: '/api/patients/{patient_id}/medications/{medication_id}/reminders',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get server status
 */
export const statusGet = <ThrowOnError extends boolean = true>(options?: Options<StatusGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<StatusGetResponses, unknown, ThrowOnError>({
        url: '/api/status',
        ...options
    });
};