// This file is auto-generated by @hey-api/openapi-ts

import type { PatientsGetResponse, DosesListResponse, DosesGetResponse } from './types.gen';

const availableDoseSchemaResponseTransformer = (data: any) => {
    data.time = new Date(data.time);
    return data;
};

const medicationSummarySchemaResponseTransformer = (data: any) => {
    if (data.last_taken_at) {
        data.last_taken_at = new Date(data.last_taken_at);
    }
    data.next_doses = data.next_doses.map((item: any) => {
        return availableDoseSchemaResponseTransformer(item);
    });
    return data;
};

const patientGetResponseSchemaResponseTransformer = (data: any) => {
    data.medications = data.medications.map((item: any) => {
        return medicationSummarySchemaResponseTransformer(item);
    });
    return data;
};

export const patientsGetResponseTransformer = async (data: any): Promise<PatientsGetResponse> => {
    data = patientGetResponseSchemaResponseTransformer(data);
    return data;
};

const createDoseSchemaResponseTransformer = (data: any) => {
    data.taken_at = new Date(data.taken_at);
    return data;
};

const doseSchemaResponseTransformer = (data: any) => {
    data.data = createDoseSchemaResponseTransformer(data.data);
    return data;
};

const patientGetDosesResponseSchemaResponseTransformer = (data: any) => {
    data.doses = data.doses.map((item: any) => {
        return doseSchemaResponseTransformer(item);
    });
    data.next_doses = data.next_doses.map((item: any) => {
        return availableDoseSchemaResponseTransformer(item);
    });
    return data;
};

export const dosesListResponseTransformer = async (data: any): Promise<DosesListResponse> => {
    data = patientGetDosesResponseSchemaResponseTransformer(data);
    return data;
};

const getDoseResponseSchemaResponseTransformer = (data: any) => {
    data.dose = doseSchemaResponseTransformer(data.dose);
    return data;
};

export const dosesGetResponseTransformer = async (data: any): Promise<DosesGetResponse> => {
    data = getDoseResponseSchemaResponseTransformer(data);
    return data;
};
