// This file is auto-generated by @hey-api/openapi-ts

export type AvailableDose = {
    /**
     * None means "we don't know the amount"
     */
    quantity?: number | null;
    time: Date;
};

export type CreateDose = {
    noted_by_user?: string | null;
    quantity: number;
    taken_at: Date;
};

export type Dose = {
    data: CreateDose;
    id: number;
};

export type DoseLimit = {
    amount: number;
    hours: number;
};

/**
 * Response for GET `/api/patients/{patient_id}/medications/{medication_id}/doses/{dose_id}`.
 */
export type GetDoseResponse = {
    dose: Dose;
    inventory?: number | null;
    medication_name: string;
    patient_name: string;
};

/**
 * Response for POST `/api/medications/`.`
 */
export type MedicationCreateResponse = {
    id: number;
};

export type MedicationSummary = {
    id: number;
    inventory?: number | null;
    last_taken_at?: Date | null;
    name: string;
    next_doses: Array<AvailableDose>;
};

export type Patient = {
    id: number;
    name: string;
};

/**
 * Request for POST `/api/patients`, PUT `/api/patients/{patient_id}`
 */
export type PatientCreateRequest = {
    name: string;
    telegram_group_id?: number | null;
};

/**
 * Response for POST `/api/patients/`.`
 */
export type PatientCreateResponse = {
    id: number;
};

/**
 * Response for GET `/api/patients/{patient_id}/medications/{medication_id}`.
 */
export type PatientGetDosesResponse = {
    doses: Array<Dose>;
    medication: PatientMedicationCreateRequest;
    next_doses: Array<AvailableDose>;
    patient_name: string;
    reminders: Reminders;
};

/**
 * Response for GET `/api/patients/{patient_id}`.
 */
export type PatientGetResponse = {
    medications: Array<MedicationSummary>;
    name: string;
    telegram_group_id?: number | null;
};

/**
 * Request for POST `/api/patients/{patient_id}/medications`
 */
export type PatientMedicationCreateRequest = {
    description?: string | null;
    dose_limits: Array<DoseLimit>;
    inventory?: number | null;
    name: string;
};

/**
 * Request for PUT `/api/patients/{patient_id}/medications`
 */
export type PatientMedicationUpdateRequest = {
    medication: PatientMedicationCreateRequest;
    reminders: Reminders;
};

export type Reminders = {
    cron_schedules: Array<string>;
};

export type MedicationCreateData = {
    body: PatientMedicationCreateRequest;
    path?: never;
    query?: never;
    url: '/api/medications';
};

export type MedicationCreateResponses = {
    /**
     * Medication created successfully
     */
    200: MedicationCreateResponse;
};

export type MedicationCreateResponse2 = MedicationCreateResponses[keyof MedicationCreateResponses];

export type MedicationDeleteData = {
    body?: never;
    path: {
        /**
         * Medication ID
         */
        id: number;
    };
    query?: never;
    url: '/api/medications/{id}';
};

export type MedicationDeleteErrors = {
    /**
     * Medication not found
     */
    404: unknown;
};

export type MedicationDeleteResponses = {
    /**
     * Medication deleted successfully
     */
    200: unknown;
};

export type PatientsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/patients';
};

export type PatientsListResponses = {
    200: Array<Patient>;
};

export type PatientsListResponse = PatientsListResponses[keyof PatientsListResponses];

export type PatientsCreateData = {
    body: PatientCreateRequest;
    path?: never;
    query?: never;
    url: '/api/patients';
};

export type PatientsCreateResponses = {
    /**
     * Patient created successfully
     */
    200: PatientCreateResponse;
};

export type PatientsCreateResponse = PatientsCreateResponses[keyof PatientsCreateResponses];

export type PatientsDeleteData = {
    body?: never;
    path: {
        /**
         * Patient ID
         */
        id: number;
    };
    query?: never;
    url: '/api/patients/{id}';
};

export type PatientsDeleteErrors = {
    /**
     * Patient not found
     */
    404: unknown;
};

export type PatientsDeleteResponses = {
    /**
     * Patient deleted successfully
     */
    200: unknown;
};

export type PatientsGetData = {
    body?: never;
    path: {
        /**
         * Patient ID
         */
        id: number;
    };
    query?: never;
    url: '/api/patients/{id}';
};

export type PatientsGetErrors = {
    /**
     * Patient not found
     */
    404: unknown;
};

export type PatientsGetResponses = {
    /**
     * Patient found successfully
     */
    200: PatientGetResponse;
};

export type PatientsGetResponse = PatientsGetResponses[keyof PatientsGetResponses];

export type PatientsUpdateData = {
    body: PatientCreateRequest;
    path: {
        /**
         * Patient ID
         */
        id: number;
    };
    query?: never;
    url: '/api/patients/{id}';
};

export type PatientsUpdateErrors = {
    /**
     * Patient not found
     */
    404: unknown;
};

export type PatientsUpdateResponses = {
    /**
     * Patient updated successfully
     */
    200: unknown;
};

export type MedicationUpdateData = {
    body: PatientMedicationUpdateRequest;
    path: {
        /**
         * Patient ID
         */
        patient_id: number;
        /**
         * Medication ID
         */
        medication_id: number;
    };
    query?: never;
    url: '/api/patients/{patient_id}/medications/{medication_id}';
};

export type MedicationUpdateErrors = {
    /**
     * Medication not found
     */
    404: unknown;
};

export type MedicationUpdateResponses = {
    /**
     * Medication updated successfully
     */
    200: unknown;
};

export type DosesListData = {
    body?: never;
    path: {
        /**
         * Patient ID
         */
        patient_id: number;
        /**
         * Medication ID
         */
        medication_id: number;
    };
    query?: never;
    url: '/api/patients/{patient_id}/medications/{medication_id}/doses';
};

export type DosesListErrors = {
    /**
     * Medication not found
     */
    404: unknown;
};

export type DosesListResponses = {
    /**
     * Doses listed successfully
     */
    200: PatientGetDosesResponse;
};

export type DosesListResponse = DosesListResponses[keyof DosesListResponses];

export type DosesRecordData = {
    body: CreateDose;
    path: {
        /**
         * Patient ID
         */
        patient_id: number;
        /**
         * Medication ID
         */
        medication_id: number;
    };
    query?: {
        /**
         * (Optional, for reminder responses) Telegram Message ID to update
         */
        reminder_message_id?: number;
    };
    url: '/api/patients/{patient_id}/medications/{medication_id}/doses';
};

export type DosesRecordErrors = {
    /**
     * Medication not found
     */
    404: unknown;
};

export type DosesRecordResponses = {
    /**
     * Dose created successfully
     */
    200: unknown;
};

export type DosesDeleteData = {
    body?: never;
    path: {
        /**
         * Patient ID
         */
        patient_id: number;
        /**
         * Medication ID
         */
        medication_id: number;
        /**
         * Dose ID
         */
        dose_id: number;
    };
    query?: never;
    url: '/api/patients/{patient_id}/medications/{medication_id}/doses/{dose_id}';
};

export type DosesDeleteErrors = {
    /**
     * Dose not found
     */
    404: unknown;
};

export type DosesDeleteResponses = {
    /**
     * Dose deleted successfully
     */
    200: unknown;
};

export type DosesGetData = {
    body?: never;
    path: {
        /**
         * Patient ID
         */
        patient_id: number;
        /**
         * Medication ID
         */
        medication_id: number;
        /**
         * Dose ID
         */
        dose_id: number;
    };
    query?: never;
    url: '/api/patients/{patient_id}/medications/{medication_id}/doses/{dose_id}';
};

export type DosesGetErrors = {
    /**
     * Dose not found
     */
    404: unknown;
};

export type DosesGetResponses = {
    /**
     * Dose fetched successfully
     */
    200: GetDoseResponse;
};

export type DosesGetResponse = DosesGetResponses[keyof DosesGetResponses];

export type DosesUpdateData = {
    body: CreateDose;
    path: {
        /**
         * Patient ID
         */
        patient_id: number;
        /**
         * Medication ID
         */
        medication_id: number;
        /**
         * Dose ID
         */
        dose_id: number;
    };
    query?: never;
    url: '/api/patients/{patient_id}/medications/{medication_id}/doses/{dose_id}';
};

export type DosesUpdateErrors = {
    /**
     * Dose not found
     */
    404: unknown;
};

export type DosesUpdateResponses = {
    /**
     * Dose updated successfully
     */
    200: unknown;
};

export type RemindersSendData = {
    body?: never;
    path: {
        /**
         * Patient ID
         */
        patient_id: number;
        /**
         * Medication ID
         */
        medication_id: number;
    };
    query?: never;
    url: '/api/patients/{patient_id}/medications/{medication_id}/remind';
};

export type RemindersSendErrors = {
    /**
     * Medication not found
     */
    404: unknown;
};

export type RemindersSendResponses = {
    /**
     * Reminder sent successfully
     */
    200: unknown;
};

export type RemindersGetData = {
    body?: never;
    path: {
        /**
         * Patient ID
         */
        patient_id: number;
        /**
         * Medication ID
         */
        medication_id: number;
    };
    query?: never;
    url: '/api/patients/{patient_id}/medications/{medication_id}/reminders';
};

export type RemindersGetErrors = {
    /**
     * Medication not found
     */
    404: unknown;
};

export type RemindersGetResponses = {
    /**
     * Reminders fetched successfully
     */
    200: Reminders;
};

export type RemindersGetResponse = RemindersGetResponses[keyof RemindersGetResponses];

export type RemindersSetData = {
    body: Reminders;
    path: {
        /**
         * Patient ID
         */
        patient_id: number;
        /**
         * Medication ID
         */
        medication_id: number;
    };
    query?: never;
    url: '/api/patients/{patient_id}/medications/{medication_id}/reminders';
};

export type RemindersSetErrors = {
    /**
     * Medication not found
     */
    404: unknown;
};

export type RemindersSetResponses = {
    /**
     * Reminders set successfully
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};
