# Copyright (C) 2026 Ohad Lutzky <lutzky@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-only

name: Deploy mkdocs
on:
  push:
    branches:
      - main

jobs:
  deploy-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements-docs.txt

      - name: Build site
        run: mkdocs build

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
