# Copyright (C) 2026 Ohad Lutzky <lutzky@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-only

name: 'Check spelling'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v7
